name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Trading101/Trading101.sln
    - name: Build
      run: dotnet build Trading101/Trading101.sln --no-restore
    - name: Test
      run: dotnet test UnitTests/UnitTests.csproj --no-build --verbosity normal
